[env:esp32-s3-devkitc1-n16r2]
platform = espressif32
board = esp32-s3-devkitc1-n16r2
framework = arduino

monitor_speed = 115200

lib_deps =
    lvgl/lvgl @ ^9.0.0
    lovyan03/LovyanGFX @ ^1.0.0

build_flags =
    -I include
    -D LV_CONF_INCLUDE_SIMPLE